# Google API YML File

maps:
  key: ABQIAAAA46JbB3rQyx9G2zgsUN04YRQxtCAne5R3u71tL7Juo0FvFqvRihRFfaF-imGwY-MJjQZ72NKdgmsEPw
  # this key is for splottr.heroku.com
  
#// Note: you will need to replace the sensor parameter below with either an explicit true or false value.
# <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=true_or_false&amp;key=ABQIAAAA46JbB3rQyx9G2zgsUN04YRQxtCAne5R3u71tL7Juo0FvFqvRihRFfaF-imGwY-MJjQZ72NKdgmsEPw" type="text/javascript"></script>
  